### PR TITLE
Implement SLAP to authenticate with Google API#2

### PR DESCRIPTION
**Pull request by chenxing1992**

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
Are system tests still failing?

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos 
Yes, it fails because travis didnt make communication with google and keep hang there waiting for replies. 

detailed issues i have posted in forum and link you up already.

**Comment by Zhiyuan-Amos** [comment]
Oh I was referring to the existing system tests, not the one about communication with Google.

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos

The existing system test all failed due to travis waiting time for responds from google was taking too long thus the testcases went haywire.

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos 

but the build.gradle works fine in importing google api

**Comment by Zhiyuan-Amos** [comment]
@chenxing1992 Is it because Travis-CI doesn't have the credentials? When you have no credentials, the default browser will be opened (see below logs) and the test will not proceed.

image

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos
But i imported the credentials into the directory and call the credential file in quickstart to authenticate. You mean travis does not know the location of the file? if so, how do i do it to let travis authenticate with the imported credentials?

**Comment by Zhiyuan-Amos** [comment]
Correct me if I'm wrong: The credentials are stored in a local directory (i.e. not on Github).

```java
private static final java.io.File DATA_STORE_DIR = new java.io.File(
            System.getProperty("user.home"), ".credentials/calendar-java-quickstart");
```

When I first started the application, I had no credentials, thus the app prompted me to sign in to my Google account. Similarly, I think that Travis has no credentials, thus the test stalls.

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos
Yes you are right, the credentials are stored in local directory but not in github. 
why is that so that you dont have credential when i imported it into the directory? how do i resolve this?

**Comment by Zhiyuan-Amos** [comment]
This is for you to debug. Upstream developers only help to debug issues with the originally forked AddressBook-Level4 :p

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos 
i get it. Thankyou so much for helping to scrutinize this issue and now im clear where the problem lies at.

**Pull request closed without merging**
