### PR TITLE
Implemented SLAP on authentication with Google API

### PR DESCRIPTION
**Pull request by chenxing1992**

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
Hi @chenxing1992, your group mate has updated Gradle to version 4.6 in his PR (#89). Since you're making a lot of changes in this PR, it's quite hard to tell what's the bug.

I think that you should try creating a PR that simply performs the import of the new libraries that you want to use. Then verify that the build passes. Then add new commits on top 1 by 1 and make sure that the build passes with each additional commit. :)

**Comment by chenxing1992** [comment]
hi @Zhiyuan-Amos, you mean i create a new PR just to upgrade gradle to 4.6 and importing of the new libraries?

**Comment by Zhiyuan-Amos** [comment]
Your groupmate's PR #89 has already updated Gradle to version 4.6, and his PR passes the Travis CI test :p 

What you can do now:
1. Create a new PR and simply commit the addition of the new libraries. Then verify if the build passes.
2. If you are familiar with Git, you actually don't need to create a new PR; you can choose to 'un-commit' all your commits here and then push the commit that adds the new libraries. :)

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos  I did a new branch out from Master which contains my teammates build.gradle. But when i check the version of gradle by ./gradlew -v is still the old version. Which im having contradiction now.

**Comment by Zhiyuan-Amos** [comment]
@chenxing1992 I'm not quite sure what causes that, but the different gradle value doesn't seem to be that thing causing your build to break. I've done a patch on my [side](https://github.com/Zhiyuan-Amos/addressbook-level4/commit/dd6fb52d80697be03cb2f503feff1204d349cbf7) whereby I added the new libraries and changed my Gradle version to 4.0.1 as per what you've [mentioned](https://github.com/nus-cs2103-AY1718S2/forum/issues/31#issuecomment-375968551) and Travis-CI [passes](https://travis-ci.org/Zhiyuan-Amos/addressbook-level4/builds/358248364).

As such, this isn't quite the same as the bug experienced in https://github.com/nus-cs2103-AY1718S2/forum/issues/31. You should try to make small changes to your code and see what causes the issue, just like the person who originally reported his [issue](https://github.com/CS2103JAN2018-W15-B1/main/pull/60) to us. The code change there is only 4 lines, as such it's much easier for us to find out what's the issue.

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos 

1st Commit (Build Sucessful): I have successfully update the gradle to download google API down and works fine in travis build. 
2nd Commit (Build Fail): I create a Quickstart.java and call it in a main.class, however, local build pass but travis fails on System test.

**Comment by chenxing1992** [comment]
@Zhiyuan-Amos  
Currently, i suspected that travis is not communicating with google API after i include test cases to test the QuickStart.java on travis but on local project it works well.

**Pull request closed without merging**
