### PR TITLE
Removed the extra "equal" signs under stories in DG

### PR DESCRIPTION
**Pull request by ghost**
Removed the extra "equal" signs under stories in the Developer Guide after apparently there was some merge conflicts as @traceurgan and I seemed to merge our PRs to the team org's "main" at the same time

### CODE REVIEW

**Comment by traceurgan** [comment]
Err i only just merged my edits a few minutes ago. I am sure my pr could not affect yours.

**Comment by HEARTOFAL1ON** [comment]
it did not, except just now the merge conflict which I resolved, but I forgot to remove the excess of "=" signs HAHA

**Comment by chenxing1992** [comment]
FYI u dont have to create a new PR just to remove one equal sign then merge again. U can still use ur old branch which has been merged before to update ur flaws.

**Comment by HEARTOFAL1ON** [comment]
how? I don't know... I only saw "reverting PR" but that isn't going to achieve what I want

**Comment by chenxing1992** [comment]
Step 1: go to source tree (if u using, which i rmb yes) 
Step 2: check out your previous branch
Step 3: commit your equal sign edits to that check out branch. 
Step 4: Push to remote repo
Step 5: pull again from that old branch (merged before)

**Comment by HEARTOFAL1ON** [comment]
okay thanks @chenxing1992, next time will try that out

**Comment by traceurgan** [comment]
Any merge conflict you had CANNOT possibly be a result of my edits. Merge conflict occur when there are commits that change the same line of code. I clearly merged AFTER you, my PR has not yet affected the team master branch. If we edited a similar line, I would have merge conflict because i merged after you. Please get your facts right before insinuating that a particular person is responsible.

**Comment by HEARTOFAL1ON** [comment]
- No one is insinuating anyone, please take your passive aggression out of here. thank you very much.
- Thank you for teaching me that because I really did not know :)
- You claim I jump to conclusions and "oppress" people but this is the classic counter-example now

**Comment by traceurgan** [comment]
Your comment: Removed the extra "equal" signs under stories in the Developer Guide after apparently there was some merge conflicts AS @traceurgan and I seemed to merge our PRs to the team org's "main" at the same time

Hi Daniel. The above sentence implies that merge conflicts arose due to us making a pr at the same time. The word "as"  as i highlighted in capital letters above, implies causality. Causality, implies responsibility.

I explained why your statement is wrong and requested that you double check before implying such causality in the future. Do explain how my comments are offensive and not suitable to be in a public space. As far as i am aware, there seems to be much more that is inappropriate with your last comment.

**Comment by HEARTOFAL1ON** [comment]
Cherry-picking on my statement. I said that it "appeared" to be merging at the same time. Yes, I claim ignorance for my mistake and I apologize for that. (let me reiterate that it takes guts to apologize)

I seriously do not know what's the beef with you since Saturday, but I am going to be the matured gentleman and walk away after this.

Also, so far all you have done is
- misunderstood me
- maligned me
- trivialized my experiences just because you have never went thru them before &
- not been as helpful as others

Please learn to walk in another person's shoes. And why so much unnecessary rage and anger? _Being angry at someone is like holding onto burning coal and wanting to intentionally throw it at someone else. It burns you_ (Buddha)

**Comment by HEARTOFAL1ON** [comment]
image

@chenxing1992 it works but why does my SourceTree look a bit funny now? My 'master' branch is 1 commit before..

Anyway, Travis CI test also passed:
image

**Review by marlenekoh — APPROVED** [review]

**Pull request merged**
